---
driver:
  name: vagrant

provisioner:
  name: chef_zero
  # You may wish to disable always updating cookbooks in CI or other testing environments.
  # For example:
  #   always_update_cookbooks: <%= !ENV['CI'] %>
  always_update_cookbooks: true

verifier:
  name: inspec

platforms:
  - name: ubuntu-16.04
  - name: centos-7.3

suites:
  - name: create-core
    run_list:
      - recipe[pacifica_docker_test::core_create]
      - recipe[pacifica_docker_test::rabbit-deploy]

  - name: create-uploader
    run_list:
      - recipe[pacifica_docker_test::uploader_create]
      - recipe[pacifica_docker_test::rabbit-deploy]

  - name: remove-core
    run_list:
      - recipe[pacifica_docker_test::core_remove]

  - name: remove-uploader
    run_list:
      - recipe[pacifica_docker_test::uploader_remove]
